app = "go-mcp-sse-proxy"
primary_region = "bom"
kill_signal = "SIGINT"
kill_timeout = "30s"
swap_size_mb = 512

[build]
dockerfile = "Dockerfile"

[deploy]
strategy = "rolling"

[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 2048

[[services]]
internal_port = 8000
protocol = "tcp"

[services.concurrency]
type = "connections"
soft_limit = 800
hard_limit = 1000

[[services.ports]]
port = 80
handlers = ["http"]
force_https = true

[[services.ports]]
port = 443
handlers = ["tls", "http"]

[[services.http_checks]]
method = "GET"
path = "/health"
interval = "30s"
timeout = "5s"
grace_period = "10s"
